package Hibernate;
// Generated 07-nov-2013 17:07:53 by Hibernate Tools 3.2.1.GA



/**
 * TbPersona generated by hbm2java
 */
public class TbPersona  implements java.io.Serializable {


     private int CI;
     private String Nom_Per;
     private String Ape_Per;
     private Integer Telefono;
     private String Direccion;

    public TbPersona() {
    }

	
    public TbPersona(int ci) {
        this.CI = ci;
    }
    public TbPersona(int ci, String nomPersona, String apePersona, Integer telefonoPersona, String direccionPersona) {
       this.CI = ci;
       this.Nom_Per = nomPersona;
       this.Ape_Per = apePersona;
       this.Telefono = telefonoPersona;
       this.Direccion = direccionPersona;
    }
   
    public int getCi() {
        return this.CI;
    }
    
    public void setCi(int ci) {
        this.CI = ci;
    }
    public String getNomPer() {
        return this.Nom_Per;
    }
    
    public void setNomPer(String nomPersona) {
        this.Nom_Per = nomPersona;
    }
    public String getApePer() {
        return this.Ape_Per;
    }
    
    public void setApePer(String apePersona) {
        this.Ape_Per = apePersona;
    }
    public Integer getTelefono() {
        return this.Telefono;
    }
    
    public void setTelefono(Integer telefonoPersona) {
        this.Telefono = telefonoPersona;
    }
    public String getDireccion() {
        return this.Direccion;
    }
    
    public void setDireccion(String direccionPersona) {
        this.Direccion = direccionPersona;
    }




}


