package Hibernate;
// Generated 08-nov-2013 11:00:59 by Hibernate Tools 3.2.1.GA



/**
 * TbRol generated by hbm2java
 */
public class TbRol  implements java.io.Serializable {


     private int CodRol;
     private String DescripcionRol;

    public TbRol() {
    }

	
    public TbRol(int codRol) {
        this.CodRol = codRol;
    }
    public TbRol(int codRol, String descripcionRol) {
       this.CodRol = codRol;
       this.DescripcionRol = descripcionRol;
    }
   
    public int getCodRol() {
        return this.CodRol;
        
    }
    
    public void setCodRol(int codRol) {
        this.CodRol = codRol;
    }
    public String getDescripcionRol() {
        return this.DescripcionRol;
    }
    
    public void setDescripcionRol(String descripcionRol) {
        this.DescripcionRol = descripcionRol;
    }




}


