package Hibernate;
// Generated 07-nov-2013 17:07:53 by Hibernate Tools 3.2.1.GA



/**
 * TbPersona generated by hbm2java
 */
public class TbUsuario  implements java.io.Serializable {


     private int CodUsuario;
     private String Cargo;
     private String Contrasenha;
     private Integer CodRol;
     private Integer CI;

    public TbUsuario() {
    }

	
    public TbUsuario(int codUsuario) {
        this.CodUsuario = codUsuario;
    }
    public TbUsuario(int codUsuario, String cargo, String contrasenha, Integer codRol, Integer Ci) {
       this.Cargo = cargo;
       this.CodUsuario = codUsuario;
       this.Contrasenha = contrasenha;
       this.CodRol = codRol;
       this.CI= Ci;
    }
   
    public String getCargo() {
        return this.Cargo;
    }
    
    public void setCargo(String cargo) {
        this.Cargo = cargo;
    }
    public int getCodUsuario() {
        return this.CodUsuario;
    }
    
    public void setCodUsuario (int codUsuario) {
        this.CodUsuario = codUsuario;
    }
    public String getContrasenha() {
        return this.Contrasenha;
    }
    
    public void setContrasenha(String contrasenha) {
        this.Contrasenha = contrasenha;
    }
    public Integer getCodRol() {
        return this.CodRol;
    }
    
    public void setCodRol(Integer codRol) {
        this.CodRol = codRol;
    }
    public Integer getCi() {
        return this.CI;
    }
    
    public void setCi (Integer ci) {
        this.CI = ci;
    }




}


